ALTER TYPE "JobStatus" ADD VALUE IF NOT EXISTS 'REVIEWING';
ALTER TYPE "JobStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "JobStatus" ADD VALUE IF NOT EXISTS 'IMPORTED';
ALTER TYPE "JobStatus" ADD VALUE IF NOT EXISTS 'DISCARDED';
ALTER TYPE "JobStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
